name: Kwiki-Revisions
version: 0.15
abstract: Kwiki Revisions Plugin
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Kwiki: 0.38
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
